apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: regatta-operator
rules:
  - apiGroups: ["regatta.dev"]
    resources: ["regattaclusters"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["regatta.dev"]
    resources: ["regattaclusters/status"]
    verbs: ["get", "patch", "update"]
  - apiGroups: ["regatta.dev"]
    resources: ["regattaclusters/finalizers"]
    verbs: ["update", "patch"]
  - apiGroups: ["apps"]
    resources: ["statefulsets"]
    verbs: ["create", "get", "list", "watch", "patch", "update", "delete"]
  - apiGroups: [""]
    resources: ["services", "configmaps"]
    verbs: ["create", "get", "list", "watch", "patch", "update", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "list", "watch", "patch", "delete"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["list", "watch"]
  - apiGroups: [""]
    resources: ["pods", "events"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
