apiVersion: v1
kind: ServiceAccount
metadata:
  name: regatta-operator
  labels:
    app.kubernetes.io/name: regatta-operator
    app.kubernetes.io/component: operator
    app.kubernetes.io/managed-by: regatta-operator
