apiVersion: v1
kind: Pod
metadata:
  name: test-runner-pod
  labels:
    app: qa-test-runner
spec:
  # Prevents Kubernetes from restarting the container if tests fail
  restartPolicy: Never
  imagePullSecrets:
    - name: ecr-secret
  containers:
    - name: test-client
      image: 694992585570.dkr.ecr.us-west-2.amazonaws.com/reg-k8s/test-client:26.0.0.789
      resources:
        requests:
          cpu: "4"
          memory: 8000M
        limits:
          cpu: "4"
          memory: 8000M
          ephemeral-storage: "8Gi"
      env:
        - name: TEST_TYPE
          # value: "smoke"
          # value: "e2e"
          value: "workload"
          # value: "qa"
        - name: TEST_PARAMS
          # value: ""
          # value: "--test_filter BroadcastFixture.* --print_type SmallOnly" # for E2E
          value: "--config /home/regatta/tools/test/config/wld_config/tpcc_config.json" # For Workload_gen
          # value: "--type python --test_name synergy/main.py --stock_rows 100 --product_sku_rows 2000000 --replenishment_rows 30000000 --connection_string 'regatta-rdb-0.regatta.svc.cluster.local:8850'" # For QA MOAW workload - Syncergy
        - name: TEST_CMD
          value: ""
        - name: SM_URL
          value: "regatta-sm.regatta.svc.cluster.local:8840"
        - name: REGATTA_CLUSTER_IPS
          value: "regatta-rdb.regatta.svc.cluster.local"
        - name: QA_REPO_COMMIT
          # value: "uri/synergy/v0" # Uri's branch with Synergy's MOAW workload
          value: ""
        - name: SOURCE_CODE_COMMIT
          value: ""
        - name: GITHUB_TOKEN
          value: ""
        - name: TIMEOUT
          value: "3600"

      # Optional: Override ENTRYPOINT if necessary (e.g., ["/bin/sh", "-c"])
      command: ["/bin/sh", "-c", "sleep 999d"]

      # Overrides Docker's CMD: Replace with your actual test command/flags
      # args:
      #   - "npm"
      #   - "test"
      #   - "--"
      #   - "--target-service=http://your-service-name.default.svc.cluster.local:8080"
